# Generated by Django 5.2.18 on 2026-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExplicacionIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("modelo", models.CharField(blank=True, max_length=60)),
                ("generado", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
