# Generated by Django 5.2.18 on 2026-10-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asistente", "0001_initial"),
        ("controles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="explicacionia",
            name="hallazgo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explicacion_ia",
                to="controles.hallazgo",
            ),
        ),
    ]
