# Generated by Django 5.2.18 on 2026-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contratista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("nit", models.CharField(blank=True, max_length=20)),
                ("contrato", models.CharField(blank=True, max_length=40)),
                ("inicio", models.DateField(blank=True, null=True)),
                ("fin", models.DateField(blank=True, null=True)),
                (
                    "honorarios_mensuales",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("honorarios_mas_iva", models.BooleanField(default=True)),
                ("alcance", models.TextField(blank=True)),
                ("exclusiones", models.TextField(blank=True)),
                (
                    "dias_informe",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="Días para entregar el informe después de la entrega mensual",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=250)),
                ("entregada_el", models.DateField()),
            ],
            options={
                "ordering": ["-entregada_el"],
            },
        ),
        migrations.CreateModel(
            name="InformeContratista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recibido_el", models.DateField()),
                ("resumen", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Observacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("respondida", "Respondida"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("respuesta", models.TextField(blank=True)),
                ("creada", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["estado", "-creada"],
            },
        ),
    ]
