# Generated by Django 5.2.18 on 2026-10-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contratistas", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrega",
            name="archivos",
            field=models.ManyToManyField(blank=True, to="empresa.archivocargado"),
        ),
        migrations.AddField(
            model_name="entrega",
            name="contratista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entregas",
                to="contratistas.contratista",
            ),
        ),
        migrations.AddField(
            model_name="entrega",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="empresa.periodo"
            ),
        ),
        migrations.AddField(
            model_name="informecontratista",
            name="archivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="empresa.archivocargado",
            ),
        ),
        migrations.AddField(
            model_name="informecontratista",
            name="entrega",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="informes",
                to="contratistas.entrega",
            ),
        ),
        migrations.AddField(
            model_name="observacion",
            name="contratista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observaciones",
                to="contratistas.contratista",
            ),
        ),
        migrations.AddField(
            model_name="observacion",
            name="informe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observaciones",
                to="contratistas.informecontratista",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entrega",
            unique_together={("contratista", "periodo")},
        ),
    ]
