# Generated by Django 5.2.18 on 2026-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Festivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "origen",
                    models.CharField(
                        default="calculado",
                        help_text="calculado (Ley 51/1983 y Pascua) o manual",
                        max_length=40,
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="Obligacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=200)),
                ("periodo_texto", models.CharField(blank=True, max_length=60)),
                (
                    "clave",
                    models.CharField(
                        help_text="Identificador único del período, ej. 2026-09",
                        max_length=60,
                    ),
                ),
                ("fecha_limite", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_preparacion", "En preparación"),
                            ("presentada", "Presentada"),
                            ("pagada", "Presentada y pagada"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                (
                    "verificacion",
                    models.CharField(
                        choices=[
                            ("dos_fuentes", "Dos fuentes coinciden"),
                            ("una_fuente", "Una fuente secundaria"),
                            (
                                "estimada",
                                "Estimada por la regla (no hay lista oficial aún)",
                            ),
                            ("no_verificada", "No verificada"),
                        ],
                        default="no_verificada",
                        max_length=15,
                    ),
                ),
                ("fuente", models.CharField(blank=True, max_length=400)),
                (
                    "laboral",
                    models.BooleanField(
                        default=False,
                        help_text="Fecha laboral/mercantil, no tributaria",
                    ),
                ),
                ("elabora", models.CharField(blank=True, max_length=120)),
                ("revisa", models.CharField(blank=True, max_length=120)),
                ("firma", models.CharField(blank=True, max_length=120)),
                ("notas", models.TextField(blank=True)),
                ("ultima_alerta", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["fecha_limite", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="ReglaVencimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obligacion", models.CharField(max_length=30)),
                (
                    "modo",
                    models.CharField(
                        choices=[
                            (
                                "dia_habil",
                                "Día hábil n del mes de vencimiento (según último dígito del NIT)",
                            ),
                            ("fecha_fija", "Fecha fija del calendario"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "digito",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Último dígito del NIT (modo día hábil)",
                        null=True,
                    ),
                ),
                ("dia_habil", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "fecha",
                    models.DateField(
                        blank=True, help_text="Solo para fecha fija", null=True
                    ),
                ),
                (
                    "periodo_clave",
                    models.CharField(
                        blank=True,
                        help_text="Solo fecha fija: 2026-B5, 2026-anual...",
                        max_length=30,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                (
                    "verificacion",
                    models.CharField(
                        choices=[
                            ("dos_fuentes", "Dos fuentes coinciden"),
                            ("una_fuente", "Una fuente secundaria"),
                            (
                                "estimada",
                                "Estimada por la regla (no hay lista oficial aún)",
                            ),
                            ("no_verificada", "No verificada"),
                        ],
                        default="no_verificada",
                        max_length=15,
                    ),
                ),
                ("fuente", models.CharField(blank=True, max_length=400)),
            ],
            options={
                "ordering": ["obligacion", "vigente_desde", "fecha"],
            },
        ),
    ]
