# Generated by Django 5.2.18 on 2026-10-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendario", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="obligacion",
            name="evidencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="obligaciones",
                to="empresa.archivocargado",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="obligacion",
            unique_together={("tipo", "clave")},
        ),
    ]
