# Generated by Django 5.2.18 on 2026-10-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendario", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obligacion",
            name="verificacion",
            field=models.CharField(
                choices=[
                    ("dos_fuentes", "Dos fuentes coinciden"),
                    (
                        "regla",
                        "Calculada con la regla del decreto (sin lista oficial contrastada)",
                    ),
                    ("una_fuente", "Una fuente secundaria"),
                    ("estimada", "Estimada por la regla (no hay lista oficial aún)"),
                    ("no_verificada", "No verificada"),
                ],
                default="no_verificada",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="reglavencimiento",
            name="verificacion",
            field=models.CharField(
                choices=[
                    ("dos_fuentes", "Dos fuentes coinciden"),
                    (
                        "regla",
                        "Calculada con la regla del decreto (sin lista oficial contrastada)",
                    ),
                    ("una_fuente", "Una fuente secundaria"),
                    ("estimada", "Estimada por la regla (no hay lista oficial aún)"),
                    ("no_verificada", "No verificada"),
                ],
                default="no_verificada",
                max_length=15,
            ),
        ),
    ]
