# Generated by Django 5.2.18 on 2026-10-09 12:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoRetencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "base_minima_uvt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tarifa_declarante",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Tarifa (%) tercero declarante",
                    ),
                ),
                (
                    "tarifa_no_declarante",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Tarifa (%) no declarante",
                    ),
                ),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("verificado", "Verificado"),
                            ("por_verificar", "Por verificar"),
                        ],
                        default="por_verificar",
                        max_length=15,
                    ),
                ),
                ("fuente", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["codigo"],
                "unique_together": {("codigo", "vigente_desde")},
            },
        ),
        migrations.CreateModel(
            name="DiferenciaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField()),
                ("concepto", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "perm_mas",
                                "Permanente que aumenta la renta (gasto no deducible, etc.)",
                            ),
                            (
                                "perm_menos",
                                "Permanente que disminuye la renta (ingreso no constitutivo, etc.)",
                            ),
                            ("temp_mas", "Temporal que aumenta la renta"),
                            ("temp_menos", "Temporal que disminuye la renta"),
                        ],
                        max_length=12,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "soporte",
                    models.CharField(
                        blank=True,
                        help_text="Norma o soporte que justifica la diferencia",
                        max_length=300,
                    ),
                ),
                ("explicada", models.BooleanField(default=False)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["anio", "concepto"],
            },
        ),
        migrations.CreateModel(
            name="Retencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("documento", models.CharField(blank=True, max_length=60)),
                ("nit", models.CharField(max_length=15)),
                ("concepto", models.CharField(max_length=30)),
                (
                    "base",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "tarifa_aplicada",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="En %",
                        max_digits=7,
                    ),
                ),
                (
                    "retenido",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "teorico",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retenciones",
                        to="empresa.archivocargado",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retenciones",
                        to="empresa.periodo",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "id"],
            },
        ),
        migrations.CreateModel(
            name="TarifaICA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ciiu", models.CharField(max_length=6)),
                ("descripcion", models.CharField(blank=True, max_length=250)),
                (
                    "tarifa_por_mil",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                ("estado", models.CharField(default="por_verificar", max_length=15)),
                ("fuente", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["ciiu"],
                "unique_together": {("ciiu", "vigente_desde")},
            },
        ),
        migrations.CreateModel(
            name="Declaracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("retefuente", "Retención en la fuente"),
                            ("iva", "IVA"),
                            ("ica", "ICA Bogotá"),
                            ("renta", "Renta y complementarios"),
                            ("exogena", "Información exógena"),
                        ],
                        max_length=12,
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField()),
                (
                    "indice",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Mes (retención), cuatrimestre/bimestre (IVA, ICA) o 1 (renta)",
                    ),
                ),
                ("formulario", models.CharField(blank=True, max_length=30)),
                (
                    "valor_propio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Valor calculado por el sistema",
                    ),
                ),
                (
                    "valor_declarado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Valor declarado por el contratista",
                    ),
                ),
                ("detalle_propio", models.JSONField(blank=True, default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador propio"),
                            ("presentada", "Presentada"),
                            ("pagada", "Pagada"),
                        ],
                        default="borrador",
                        max_length=12,
                    ),
                ),
                ("elabora", models.CharField(blank=True, max_length=120)),
                ("revisa", models.CharField(blank=True, max_length=120)),
                ("firma", models.CharField(blank=True, max_length=120)),
                ("presentada_el", models.DateField(blank=True, null=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "evidencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="declaraciones",
                        to="empresa.archivocargado",
                    ),
                ),
            ],
            options={
                "ordering": ["-anio", "tipo", "-indice"],
                "unique_together": {("tipo", "anio", "indice")},
            },
        ),
    ]
