# Generated by Django 5.2.18 on 2026-10-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impuestos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaracion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("retefuente", "Retención en la fuente"),
                    ("iva", "IVA"),
                    ("ica", "ICA Bogotá"),
                    ("reteica", "ReteICA Bogotá"),
                    ("renta", "Renta y complementarios"),
                    ("exogena", "Información exógena nacional (DIAN)"),
                    ("exogena_distrital", "Información exógena distrital (Bogotá)"),
                ],
                max_length=20,
            ),
        ),
    ]
