# Generated by Django 5.2.18 on 2026-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estimacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impuesto", models.CharField(max_length=15)),
                ("anio", models.PositiveSmallIntegerField()),
                (
                    "escenario",
                    models.CharField(
                        choices=[
                            ("base", "Base"),
                            ("favorable", "Favorable"),
                            ("adverso", "Adverso"),
                        ],
                        default="base",
                        max_length=10,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "minimo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "maximo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("supuestos", models.JSONField(blank=True, default=dict)),
                ("advertencias", models.JSONField(blank=True, default=list)),
                ("calculado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["impuesto", "escenario"],
            },
        ),
        migrations.CreateModel(
            name="Simulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("anio", models.PositiveSmallIntegerField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("ajustes", models.JSONField(default=dict)),
                ("resultado", models.JSONField(default=dict)),
                ("es_estimacion", models.BooleanField(default=True, editable=False)),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
    ]
