# Generated by Django 5.2.18 on 2026-10-09 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analitica", "0001_initial"),
        ("empresa", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="estimacion",
            name="corte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estimaciones",
                to="empresa.periodo",
            ),
        ),
        migrations.AddField(
            model_name="simulacion",
            name="autor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="simulacion",
            name="corte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="empresa.periodo"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="estimacion",
            unique_together={("impuesto", "anio", "corte", "escenario")},
        ),
    ]
