# Generated by Django 5.2.18 on 2026-10-09 12:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentido",
                    models.CharField(
                        choices=[
                            ("emitida", "Emitida (ventas)"),
                            ("recibida", "Recibida (compras)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("factura", "Factura"),
                            ("nota_credito", "Nota crédito"),
                            ("nota_debito", "Nota débito"),
                            ("doc_soporte", "Documento soporte"),
                        ],
                        default="factura",
                        max_length=15,
                    ),
                ),
                ("prefijo", models.CharField(blank=True, max_length=10)),
                ("numero", models.CharField(max_length=30)),
                ("cufe", models.CharField(blank=True, max_length=130)),
                ("fecha", models.DateField()),
                ("nit_emisor", models.CharField(max_length=15)),
                ("nombre_emisor", models.CharField(blank=True, max_length=250)),
                ("nit_receptor", models.CharField(max_length=15)),
                ("nombre_receptor", models.CharField(blank=True, max_length=250)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "retenciones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("estado_dian", models.CharField(blank=True, max_length=40)),
                (
                    "documento_afectado",
                    models.CharField(
                        blank=True,
                        help_text="Factura que corrige una nota crédito/débito",
                        max_length=40,
                    ),
                ),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="empresa.archivocargado",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="empresa.periodo",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "prefijo", "numero"],
                "indexes": [
                    models.Index(
                        fields=["periodo", "sentido"],
                        name="facturacion_periodo_1d5b6e_idx",
                    )
                ],
            },
        ),
    ]
