# Generated by Django 5.2.18 on 2026-10-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contabilidad", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimiento",
            name="archivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="empresa.archivocargado",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="cuenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="contabilidad.cuenta",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="empresa.periodo",
            ),
        ),
        migrations.AddField(
            model_name="saldocuenta",
            name="archivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="saldos",
                to="empresa.archivocargado",
            ),
        ),
        migrations.AddField(
            model_name="saldocuenta",
            name="cuenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="saldos",
                to="contabilidad.cuenta",
            ),
        ),
        migrations.AddField(
            model_name="saldocuenta",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="saldos",
                to="empresa.periodo",
            ),
        ),
        migrations.AddIndex(
            model_name="movimiento",
            index=models.Index(
                fields=["periodo", "cuenta"], name="contabilida_periodo_891410_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saldocuenta",
            index=models.Index(
                fields=["periodo", "cuenta"], name="contabilida_periodo_29d3bb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saldocuenta",
            unique_together={("archivo", "cuenta")},
        ),
    ]
