# Generated by Django 5.2.18 on 2026-10-09 12:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoBanco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.CharField(blank=True, max_length=300)),
                ("referencia", models.CharField(blank=True, max_length=60)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_banco",
                        to="empresa.archivocargado",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_banco",
                        to="empresa.periodo",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "id"],
            },
        ),
    ]
