# Generated by Django 5.2.18 on 2026-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tercero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="NIT / cédula (sin DV)"
                    ),
                ),
                ("dv", models.CharField(blank=True, max_length=1, verbose_name="DV")),
                ("razon_social", models.CharField(blank=True, max_length=250)),
                (
                    "tipo_persona",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("juridica", "Persona jurídica"),
                            ("natural", "Persona natural"),
                            ("", "Sin definir"),
                        ],
                        max_length=10,
                    ),
                ),
                ("regimen", models.CharField(blank=True, max_length=60)),
                (
                    "es_declarante",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Declarante de renta"
                    ),
                ),
                ("es_autorretenedor", models.BooleanField(default=False)),
                ("direccion", models.CharField(blank=True, max_length=200)),
                ("ciudad", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=40)),
                ("ciiu", models.CharField(blank=True, max_length=6)),
                ("origen", models.CharField(blank=True, max_length=30)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["razon_social", "nit"],
            },
        ),
    ]
