# Generated by Django 5.2.18 on 2026-10-09 12:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import empresa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="NIT (sin DV)"
                    ),
                ),
                ("dv", models.CharField(max_length=1, verbose_name="DV")),
                ("razon_social", models.CharField(max_length=200)),
                ("domicilio", models.CharField(blank=True, max_length=120)),
                ("representante_legal", models.CharField(blank=True, max_length=120)),
                ("revisor_fiscal", models.CharField(blank=True, max_length=120)),
                ("contador", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "verbose_name_plural": "empresa",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("dueno", "Dueño / administrador"),
                            ("contador", "Contador o revisor (solo lectura)"),
                            ("asistente", "Asistente de carga"),
                            ("consulta", "Consulta"),
                            ("contratista", "Contratista (acceso limitado)"),
                        ],
                        default="consulta",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=60)),
                ("descripcion", models.CharField(blank=True, max_length=250)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("decimal", "Decimal"),
                            ("entero", "Entero"),
                            ("texto", "Texto"),
                            ("lista", "Lista (separada por comas)"),
                        ],
                        default="decimal",
                        max_length=10,
                    ),
                ),
                ("valor", models.TextField(blank=True)),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("verificado", "Verificado"),
                            ("por_verificar", "Por verificar"),
                        ],
                        default="por_verificar",
                        max_length=15,
                    ),
                ),
                ("fuente", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["codigo", "-vigente_desde"],
                "unique_together": {("codigo", "vigente_desde")},
            },
        ),
        migrations.CreateModel(
            name="PerfilImportacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=20)),
                (
                    "hoja",
                    models.CharField(
                        blank=True, help_text="Vacío = primera hoja", max_length=60
                    ),
                ),
                ("fila_encabezado", models.PositiveSmallIntegerField(default=1)),
                ("separador_csv", models.CharField(default=",", max_length=3)),
                (
                    "decimal_coma",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar si el archivo usa punto para miles y coma para decimales.",
                        verbose_name="Decimales con coma (1.234,56)",
                    ),
                ),
                (
                    "formato_fecha",
                    models.CharField(
                        blank=True,
                        help_text="Ej. %d/%m/%Y. Vacío = automático",
                        max_length=20,
                    ),
                ),
                ("mapeo", models.JSONField(blank=True, default=dict)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["tipo", "nombre"],
                "unique_together": {("nombre", "tipo")},
            },
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                ("mes", models.PositiveSmallIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_revision", "En revisión"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="abierto",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "ordering": ["-anio", "-mes"],
                "unique_together": {("anio", "mes")},
            },
        ),
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_texto", models.CharField(blank=True, max_length=150)),
                ("accion", models.CharField(max_length=30)),
                ("modelo", models.CharField(blank=True, max_length=80)),
                ("objeto_id", models.CharField(blank=True, max_length=60)),
                ("descripcion", models.CharField(blank=True, max_length=300)),
                ("detalle", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "fecha",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ArchivoCargado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("balance", "Balance de prueba (World Office)"),
                            ("auxiliar", "Auxiliares (World Office)"),
                            ("facturas_dian", "Facturas electrónicas (Excel DIAN)"),
                            ("facturas_xml", "Facturas electrónicas (XML)"),
                            ("retenciones", "Retenciones practicadas"),
                            ("extracto_banco", "Extracto bancario"),
                            ("declaracion", "Declaración / borrador del contratista"),
                            ("otro", "Otro soporte"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        max_length=300, upload_to=empresa.models.ruta_carga
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("hash_sha256", models.CharField(db_index=True, max_length=64)),
                ("tamano", models.PositiveBigIntegerField(default=0)),
                ("origen", models.CharField(blank=True, max_length=60)),
                ("sentido", models.CharField(blank=True, max_length=10)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de confirmar"),
                            ("importado", "Importado"),
                            ("error", "Con errores"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("vigente", models.BooleanField(default=False)),
                ("resumen", models.JSONField(blank=True, default=dict)),
                ("errores", models.JSONField(blank=True, default=list)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="empresa.perfilimportacion",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archivos",
                        to="empresa.periodo",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo", "hash_sha256"),
                        name="archivo_unico_por_tipo_hash",
                    )
                ],
            },
        ),
    ]
