# Generated by Django 5.2.18 on 2026-10-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivocargado",
            name="formulario",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="archivocargado",
            name="verificaciones",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
