# Generated by Django 5.2.18 on 2026-10-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_carga_verificaciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivocargado",
            name="varios_meses",
            field=models.BooleanField(
                default=False,
                help_text="Facturas de varios meses: se reparten por su fecha de emisión",
            ),
        ),
    ]
