# Generated by Django 5.2.18 on 2026-10-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_carga_varios_meses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivocargado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("balance", "Balance de prueba (World Office)"),
                    ("auxiliar", "Auxiliares (World Office)"),
                    ("facturas_dian", "Facturas electrónicas (Excel DIAN)"),
                    ("facturas_xml", "Facturas electrónicas (XML)"),
                    ("retenciones", "Retenciones practicadas"),
                    ("extracto_banco", "Extracto bancario"),
                    ("terceros", "Maestro de terceros (World Office o plantilla)"),
                    ("declaracion", "Declaración / borrador del contratista"),
                    ("otro", "Otro soporte"),
                ],
                max_length=20,
            ),
        ),
    ]
