# Generated by Django 5.2.18 on 2026-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hallazgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        help_text="Identifica el registro afectado; permite no duplicar",
                        max_length=200,
                    ),
                ),
                ("titulo", models.CharField(max_length=250)),
                ("detalle", models.TextField(blank=True)),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta (rojo)"),
                            ("media", "Media (ámbar)"),
                            ("baja", "Baja (verde)"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("explicado", "Explicado"),
                            ("corregido", "Corregido"),
                        ],
                        default="abierto",
                        max_length=10,
                    ),
                ),
                ("explicacion", models.TextField(blank=True)),
                ("cifras", models.JSONField(blank=True, default=dict)),
                ("evidencia", models.JSONField(blank=True, default=dict)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("detectado_ultima_vez", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["estado", "severidad", "-actualizado"],
            },
        ),
        migrations.CreateModel(
            name="ReglaControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("grupo", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta (rojo)"),
                            ("media", "Media (ámbar)"),
                            ("baja", "Baja (verde)"),
                        ],
                        default="media",
                        max_length=6,
                    ),
                ),
                ("norma", models.CharField(blank=True, max_length=300)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["grupo", "codigo"],
            },
        ),
    ]
