# Generated by Django 5.2.18 on 2026-10-09 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("controles", "0001_initial"),
        ("empresa", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hallazgo",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hallazgos",
                to="empresa.periodo",
            ),
        ),
        migrations.AddField(
            model_name="hallazgo",
            name="resuelto_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hallazgo",
            name="regla",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hallazgos",
                to="controles.reglacontrol",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hallazgo",
            unique_together={("regla", "periodo", "clave")},
        ),
    ]
